spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate: null
      show_sql: true
      dialect: org.hibernate.dialect.OracleDialect
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: 91788
    driver-class-name: oracle.jdbc.driver.OracleDriver
